### PR TITLE
Improve doc for web UI

### PR DESCRIPTION
**Pull request by thomasluquet**
I just add the link and an image on the readme.

### CODE REVIEW

**Comment by FrostyCoolSlug** [comment]
I'd like to put a hold on this MR, and revisit it a little later on, the UI included with the Daemon is an early preview at best and hasn't been through a proper release cycle yet (it was added after alpha1), there have been a huge number of changes and tweaks since then. It would make more sense to add this once the UI is complete (and we've made the repo public).

**Comment by thomasluquet** [comment]
i have written that's feature is in beta. Perhaps we can write more clearly it not  fully functional now ?

I send this MR, because i forgot the port of UI. 

And, I think that for security reasons, it could be interesting to indicate that a web port opens when you launch the daemon

**Comment by lm41** [comment]
> And, I think that for security reasons, it could be interesting to indicate that a web port opens when you launch the daemon

In think the posibility to start the web server will be optional in the future.

**Comment by FrostyCoolSlug** [comment]
You're right, we should mention that by default a web server is loaded and should expand on the reasoning (for serving the configuration tool), although with that being said, I think we should exclude a screenshot of the webui for the time being.

**Comment by FrostyCoolSlug** [comment]
I'm going to close this for now, I've rewritten a chunk of the README prior to the 0.2.0 release, which includes details about the WebUI, as well as instructions for turning it off. Going forward, I'm going to be using feature branches rather than pushing directly to main, which should prevent situations like this happening!

**Pull request closed without merging**
